# Generated by Django 4.2.11 on 2024-03-18 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.CharField(help_text='Board 컨텐츠', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='create_ts',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 시간'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(help_text='Board 제목', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='update_ts',
            field=models.DateTimeField(auto_now=True, help_text='수정 시간'),
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(help_text='CustomUser Foreign Key', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
